baseurl = "https://lartpang.github.io/blog"
DefaultContentLanguage = "en"
title = "Lart Pang's Articles..."
theme = "beautifulhugo"
metaDataFormat = "yaml"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
# pygmentsUseClassic = true
# pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "胡言乱语" # Set a different text for the header on the home page
  subtitle = "竟然被你找到了！"
  mainSections = ["post", "posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
[[Params.bigimg]]
 src = "img/home.gif"
 desc = "Lart Pang"
 # position: see values of CSS background-position.
 position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Lart Pang"
  github = "https://github.com/lartpang"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "Sites"
    name = "Other Sites"
    weight = 2
[[menu.main]]
    parent = "Sites"
    name = "CSDN"
    url = "https://blog.csdn.net/p_lart"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4
