name: build the website

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    name: Generate blog
    runs-on: ubuntu-20.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id || github.event_name == 'schedule' }}
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies and Generate new html
        run: |
          cd scripts/
          pip install --upgrade pip
          pip install -r requirements.txt
          python issue2md.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} --issue_number '${{ github.event.issue.number }}'

      - name: update html
        run: |
          git config --local user.email "action-bot@github.com"
          git config --local user.name "${{ github.repository_owner }}"
          git add .
          git commit -a -m '🎉auto update' || echo "nothing to commit"
          git push || echo "nothing to push"
          sleep 3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/."
